print("Welcome to the Plumbing Job Quote Calculator")
hours_worked = float(input("How many hours did you work? "))
hourly_rate = float(input("What is your hourly rate? $"))
cost_of_materials = float(input("What was the total cost of materials? $"))
sales_tax = float(input("What is the sales tax %? "))
labor = round(hours_worked * hourly_rate, 2)
materials = round(cost_of_materials * (sales_tax / 100 + 1), 2)
total_quote = round(labor + materials, 2)
print(f"Your quote is:\nLabor: ${labor:.2f}\nMaterials (with tax): ${materials:.2f}\nTotal cost: ${total_quote:.2f}")
